// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/index": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/index";
  };
  "routes/HomePage.tsx": {
    id: "routes/HomePage";
    page: "/";
  };
  "routes/IndexPage.tsx": {
    id: "routes/IndexPage";
    page: "/index";
  };
};