// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/index": {
    params: {};
  };
  "/checkout": {
    params: {};
  };
  "/detalle-libro": {
    params: {};
  };
  "/panel-crud": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/index" | "/checkout" | "/detalle-libro" | "/panel-crud";
  };
  "routes/HomePage.tsx": {
    id: "routes/HomePage";
    page: "/";
  };
  "routes/IndexPage.tsx": {
    id: "routes/IndexPage";
    page: "/index";
  };
  "routes/CheckoutPage.tsx": {
    id: "routes/CheckoutPage";
    page: "/checkout";
  };
  "routes/BookDetailPage.tsx": {
    id: "routes/BookDetailPage";
    page: "/detalle-libro";
  };
  "routes/PanelCRUDPage.tsx": {
    id: "routes/PanelCRUDPage";
    page: "/panel-crud";
  };
};