// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/checkout": {
    params: {};
  };
  "/detalle-libro": {
    params: {};
  };
  "/panel-crud": {
    params: {};
  };
  "/registrar": {
    params: {};
  };
  "/carrito": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/login" | "/checkout" | "/detalle-libro" | "/panel-crud" | "/registrar" | "/carrito";
  };
  "routes/HomePage.tsx": {
    id: "routes/HomePage";
    page: "/";
  };
  "routes/LoginPage.tsx": {
    id: "routes/LoginPage";
    page: "/login";
  };
  "routes/CheckoutPage.tsx": {
    id: "routes/CheckoutPage";
    page: "/checkout";
  };
  "routes/BookDetailPage.tsx": {
    id: "routes/BookDetailPage";
    page: "/detalle-libro";
  };
  "routes/PanelCRUDPage.tsx": {
    id: "routes/PanelCRUDPage";
    page: "/panel-crud";
  };
  "routes/RegisterPage.tsx": {
    id: "routes/RegisterPage";
    page: "/registrar";
  };
  "routes/CartPage.tsx": {
    id: "routes/CartPage";
    page: "/carrito";
  };
};